### ISSUE TITLE
Build autoconf errors on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by drone1** [realh/normalmap#3]
Hi there. I'd love to check this software out but am having some trouble. 

I googled around a bit but installing 'libtool' did not fix the issues as one post said.

Without further ado:

```
➜  dev git clone https://github.com/realh/normalmap.git                              
Cloning into 'normalmap'...
remote: Enumerating objects: 204, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 204 (delta 1), reused 3 (delta 1), pack-reused 196
Receiving objects: 100% (204/204), 1.22 MiB | 499.00 KiB/s, done.
Resolving deltas: 100% (114/114), done.
➜  dev normalmap 
➜  normalmap git:(master) ls
AUTHORS  ChangeLog  configure.ac  COPYING  INSTALL  Makefile.am  mkycmflags  NEWS  README  README.md  src  win32
➜  normalmap git:(master) autoconf
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
➜  normalmap git:(master) 
➜  normalmap git:(master) autoconf #running again 'works'
➜  normalmap git:(master) ./configure
configure: error: cannot find required auxiliary files: config.guess config.sub
➜  normalmap git:(master) 
```

As you can see, running ``autoconf`` the second time emits no errors (odd?), but then ./configure does not work.

I installed autoconf and ``automake`` just today with ``sudo apt upgrade && sudo apt install autoconf && sudo apt install automake``

Any suggestions?

Thank you!

**Comment by realh** [comment]
Try running `autoreconf -i -f`, which automatically works out what else it needs to run besides autoconf eg automake, libtoolize. The -i makes it install those auxiliary files into the project, which you seem to be missing at the moment, while -f forces it to update any files that might have become outdated.

**Comment by drone1** [comment]
Thanks for the quick reply. Unfortunately it did not work:

```
➜  dev git clone https://github.com/realh/normalmap.git
Cloning into 'normalmap'...
remote: Enumerating objects: 204, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 204 (delta 1), reused 3 (delta 1), pack-reused 196
Receiving objects: 100% (204/204), 1.22 MiB | 4.19 MiB/s, done.
Resolving deltas: 100% (114/114), done.
➜  dev cd normalmap 
➜  normalmap git:(master) autoconf -i -f
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

**Comment by drone1** [comment]
In case this is useful to you: autoconf version is 2.71. Thank you!

**Comment by realh** [comment]
You need to run auto**re**conf, not just autoconf.

**Comment by drone1** [comment]
Oops, got it. Should have copy-pasted that! After installing popt, I got it all ./configure'd, compiled & installed. Thanks so much for the help!

**Comment by drone1** [comment]
Exactly what I needed. Thank you so much. Have a great day!
